[tool.poetry]
name = "piano-tiles"
version = "0.1.0"
description = ""
authors = ["froshy <rgl78@cornell.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
